# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180627_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='created_at',
        ),
    ]
